//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bushman.RevitDevTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bushman.RevitDevTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string _auto_location {
            get {
                return ResourceManager.GetString("_auto_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bushman.RevitDevTools..
        /// </summary>
        public static string _aviability_type {
            get {
                return ResourceManager.GetString("_aviability_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        public static string _Button_caption {
            get {
                return ResourceManager.GetString("_Button_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _Button_image {
            get {
                object obj = ResourceManager.GetObject("_Button_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command long description..
        /// </summary>
        public static string _Button_long_description {
            get {
                return ResourceManager.GetString("_Button_long_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _Button_tooltip_image {
            get {
                object obj = ResourceManager.GetObject("_Button_tooltip_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command default tooltip text..
        /// </summary>
        public static string _Button_tooltip_text {
            get {
                return ResourceManager.GetString("_Button_tooltip_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is default message..
        /// </summary>
        public static string _command_message {
            get {
                return ResourceManager.GetString("_command_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help\RevitDevTools.chm.
        /// </summary>
        public static string _Help_file_name {
            get {
                return ResourceManager.GetString("_Help_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default_command.
        /// </summary>
        public static string _Help_topic_Id {
            get {
                return ResourceManager.GetString("_Help_topic_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string _message {
            get {
                return ResourceManager.GetString("_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ribbon panel.
        /// </summary>
        public static string _Ribbon_panel_name {
            get {
                return ResourceManager.GetString("_Ribbon_panel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RevitDevTools.
        /// </summary>
        public static string _Ribbon_tab_name {
            get {
                return ResourceManager.GetString("_Ribbon_tab_name", resourceCulture);
            }
        }
    }
}
